### ISSUE TITLE
Frequency vs. Cardinality in Get_Mapping_Position function of IPLoM implementation

### ISSUE THREAD

**Issue by pigeek** [logpai/logparser#35]
In Get_Mapping_Position line 514. The comment says: "If the frequency of the freq_card>1 then", which is also aligned with the algorithm in the original paper.
```   
# If the frequency of the freq_card>1 then
if maxIdx > 1:
````
However, in the code maxIdx is used, which, for my understanding, represents the cardinality itself and not its frequency. I believe its frequency value is in maxCount and therefore maxCount should be used to check if it's greater than 1. Or I am misinterpreting the implementation?

**Comment by PinjiaHe** [comment]
The card with the highest frequency (not its frequency) is what we want here, so it is _maxIdx_.

FYI, the definition of freq_card in the original paper:

> Determine the token count value with the highest frequency other than value 1 as _freq card_.

**Comment by pigeek** [comment]
The paper  says:

> if the frequency of freq card > 1 then

So it's frequency, not the card

**Comment by PinjiaHe** [comment]
The pseudo code in the original paper is a little bit confusing:

> **else** {the frequency of _freq card_ = 1}

Based on the definition, we know the  "frequency" of freq_card cannot be 1. Thus, we think the author actually refers to the value of freq_card. That's why we use maxIdx in the implementation. However, to align with the original paper's pseudo code, we use the same comment. Hope that the explanation helps.
